### ISSUE TITLE
Shared Library Linking problem on OSX

### ISSUE THREAD

**Issue by kosack** [cta-observatory/pyhessio#1]
(summarized and migrated this issue from the old repo)

On OSX when installing via `conda`, the package cannot be imported due to an incorrect *rpath*in `pyhessioc.so` or in `libhessio.dylib`.  The problem is that `libhessio.dylib` cannot be found, though it is installed in `anaconda/lib`.

```
OSError: dlopen(/Users/x/anaconda/lib/python3.4/site-packages/pyhessio-0.2-py3.4-macosx-10.5-x86_64.egg/pyhessio/pyhessioc.so, 6):
 Library not loaded: @rpath/./libhessio.dylib
  Referenced from: /Users/x/anaconda/lib/python3.4/site-packages/pyhessio-0.2-py3.4-macosx-10.5-x86_64.egg/pyhessio/pyhessioc.so
  Reason: image not found
```

Apparently, anaconda handles it's virtual environments by updating the internal linking path of all shared libraries (see e.g. https://github.com/conda/conda-build/issues/279). 

Having an `@rpath` directive should work, but for some reason it does not here. This may be related to the extra `./` in the path, or the warning given during the build:

```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   hessio
```

**Comment by kosack** [comment]
I was able to manually get it to work by the following (though I didn't test it with virtual envs):

```
cd ~/anaconda/lib/python3.4/site-packages/pyhessio-0.2-py3.4-macosx-10.5-x86_64.egg/pyhessio
install_name_tool  --change @rpath/./libhessio.dylib @loader_path../../../../libhessio.dylib pyhessioc.so
``` 

then verified that the change was made:

```
> otool -L pyhessioc.so

pyhessioc.so:
	@loader_path/../../../../libhessio.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

After that, it worked.

**Comment by jacquemier** [comment]
As soon as I will have an acces to a MacOSX system , I will try this:
http://conda.pydata.org/docs/building/shared-libraries.html

**Comment by kosack** [comment]
You might want to try installing an OSX virtual machine using vagrant (they seem to have one in their repo).   www.vagrantup.com, and see https://atlas.hashicorp.com/boxes/search to find an OSX box that will be automatically downloaded, installed, and booted up.

**Comment by ohma81** [comment]
Small add-on to Karls manual fix. I had to also change `@loader_path` when using a non-virtual environment with anaconda. The following did the trick for me:

`cd /path/to/pyhessio/installation/pyhessio 
install_name_tool -change @loader_path~/anaconda/lib/libhessio.dylib /Users/x/anaconda/lib/libhessio.dylib pyhessioc.so`

**Comment by kosack** [comment]
This clearly isn't an issue with other C++ shared libraries installed via anaconda, so there must be a "correct" way to do it so that it works automatically...  Hopefully we can solve it.

**Comment by jacquemier** [comment]
I finally found a workaround.
I simplified compilation process by removed CMake call for hessioxxx library.
Now, hessioxxx source code is compiled with pyhessio.c (wrapper code) dirrectly in setup.py.

version -> 0.5.0
