### ISSUE TITLE
Number of photoelectrons at each pixel

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/pyhessio#13]
Extract MCEvent.mc_pe_list[tel].pe_count[pix] into a mc-event object.

**Comment by jacquemier** [comment]
pyhessio only returns numeric values, never object.
But I will implement the getter  MCEvent.mc_pe_list[tel].pe_count[pix] inside pyhessio.
Then filling mc-event with this value has to be implemented in ctapipe

**Comment by jacquemier** [comment]
I have implemented the getter for MCEvent.mc_pe_list[tel].pe_count[pix].
But in hessio simulation file, these values are always equal to zero.
You should ask to Konrad Bernloehr (MPI Heidelberg) why and if there is a way to fill them.

**Comment by watsonjj** [comment]
Hi Jean, thanks for implementing this. Are you sure they are ALL equal to 0? The extreme majority should be 0, but there should be some that are not. I will try to have a look myself.

**Comment by jacquemier** [comment]
Effectively, I had not check they are ALL equal to 0.

**Comment by GernotMaier** [comment]
I think we usually do not write out the pe, is it would increase the size of the output file significantly. This would require a special simulation run.

**Comment by watsonjj** [comment]
Ah okay. I already have such a simulation run. Can this addition be committed yet?

**Comment by jacquemier** [comment]
I have just merge the PULL request.
So yes this addition is committed yet.
Please let me know if values are correct with your special simulation run.

**Comment by kosack** [comment]
Is the PE count the same things as applying the calibration to the digital counts?

see `read_hessio_single_tel.py` in the apply_mc_calib function (it's just `image_pe = (image_dc - peds) * gains`, which is pretty easy to do - you don't really need a separate function to read this from the MC)

**Comment by watsonjj** [comment]
Hi Karl, no it is different. It is what you should get if your charge extraction and calibration was perfect. I believe it is the true number of photoelectrons after the photocathode for that event in the simulation.

**Comment by watsonjj** [comment]
And is only the cherenkov photoelectrons, not any NSB. I use it to compare the success of different charge extraction techniques.

**Comment by kosack** [comment]
Ah, ok, then it definitely makes sense to have a readout for it.
