### ISSUE TITLE
add sphinx documentation

### ISSUE THREAD

**Issue by kosack** [cta-observatory/pyhessio#28]
It would be good to document the pyhessio API using sphinx so the list of functions and descriptions appear on a web page. 

The API (list of C and python functions and return values) is being proposed as a standard for CTA data readers/writers, so it would be very useful to have documentation. 

In principle that just means making sure there are docstrings everywhere and running `sphinx-quickstart` to setup sphinx.

**Comment by jacquemier** [comment]
https://cta-observatory.github.io/pyhessio
