### ISSUE TITLE
trouble using pyhessio

### ISSUE THREAD

**Issue by GernotMaier** [cta-observatory/pyhessio#4]
Hello,

this is very likely a trivial question: I've installed pyhessio as described in the README using  Anaconda. Do I have to make additions to PYTHONPATH or LD_LIBRARY_PATH to use pyhessio? I am getting import errors when I try to use it in ctapipe ('ImportError: No module named 'hessio'').

Cheers.

Gernot

**Comment by jacquemier** [comment]
Heloo, 

Os which system are you running ? 
On Linux you do not need to set a PYTHONPATH or LD_LIBRARY_PATH . 

On MacOsX Karl has a similary issue with this workaround: 

https://github.com/cta-observatory/pyhessio/issues/1 


Cheers, Jean 

----- Mail original -----

De: "GernotMaier" <notifications@github.com> 
À: "cta-observatory/pyhessio" <pyhessio@noreply.github.com> 
Envoyé: Mardi 24 Novembre 2015 11:30:24 
Objet: [pyhessio] trouble using pyhessio (#4) 



Hello, 

this is very likely a trivial question: I've installed pyhessio as described in the README using Anaconda. Do I have to make additions to PYTHONPATH or LD_LIBRARY_PATH to use pyhessio? I am getting import errors when I try to use it in ctapipe ('ImportError: No module named 'hessio''). 

Cheers. 

Gernot

**Comment by GernotMaier** [comment]
Linux.

**Comment by jacquemier** [comment]
Does this error occur whatever the current directory? Or only in
pyhessio  directory?

**Comment by jacquemier** [comment]
This error occurs when you use ctapipe ? 
If yes, you need to update ctapipe which now uses pyhessio and no more hessio.

**Comment by GernotMaier** [comment]
Yes - I know it was something trivial. I needed to change hessio to pyhessio... Thanks for the help!

Gernot
