### ISSUE TITLE
Anaconda install not available for python 3.5

### ISSUE THREAD

**Issue by TarekHC** [cta-observatory/pyhessio#43]
Hi all, 

Currently, within the ctapipe "installation for developers", the version that is stated is python 3.5. But now I'm trying to install pyhessio using conda (which is also the method described) and it is not working.

```
>conda install pyhessio
Fetching package metadata ...........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - pyhessio

You can search for packages on anaconda.org with

    anaconda search -t conda pyhessio
```

I tested, and the installation works using python 3.4.5. 

I know that I can install it via gitHub clone and "python setup.py install", but then documentation should be fixed.

So is there a problem with python 3.5? Or is this easily fixed?

Thanks in advance!

Tarek

**Comment by mackaiver** [comment]
> I tested, and the installation works using python 3.4.5.

This does not work for me. I'm using a mac however.

**Comment by jacquemier** [comment]
I have just upload pyhessio to anaconda cloud for user cta-observatory [here](https://anaconda.org/cta-observatory/pyhessio/files)
Please try again with the following command:
conda install -c cta-observatory pyhessio

**Comment by TarekHC** [comment]
Indeed, now it works.

Thank you @jacquemier !!
