### ISSUE TITLE
Install problem with anaconda

### ISSUE THREAD

**Issue by jjlk** [cta-observatory/pyhessio#9]
Dear all,

I'm trying to install the pyhessio module to start working with ctapipe. I'm following these instructions (https://cta-observatory.github.io/ctapipe/getting_started/index.html): 
`git clone https://github.com/cta-observatory/pyhessio`
`conda build pyhessio`
`conda install --use-local pyhessio`
The last command returns an error linked to conflict packages: 

(cta)[julien@touques] ctasoft $ conda install --use-local pyhessio
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .......
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|#################################################################################################################################| 100%

Hint: the following packages conflict with each other:
  - pyhessio
  - python 3.5*

Use 'conda info pyhessio' etc. to see the dependencies for each package.

Do you have any idea how to fix this ? For informations, I'm using Mac OS X 10.11.3 and the latest version of anaconda (for python2.7 but I created a virtual environment as suggested in the previous link). You can find the log of the build command in the attached file [log_build.txt](https://github.com/cta-observatory/pyhessio/files/167507/log_build.txt).

Best regards,

Julien

**Comment by jacquemier** [comment]
I can reproduce this issue.
As a workaround you can do:
source activate  cta 
cd pyhessio
python setup.py install

**Comment by jjlk** [comment]
Thanks, the solution works fine.

**Comment by jacquemier** [comment]
When you install anaconda, you get it for a specific version of python.
Today (March 10 2016) is python 3.5

But few weeks ago it was for python 3.4
If you have installed anaconda for python 3.4 you can not build conda package for python version upper to 3.4.


So you have the choice: 

Either you create a conda env for python 3.4, and build pyhessio for python 3.4.: 
#conda create -n cta python=3.4 astropy matplotlib scipy scikit-learn numba cython

Or you uninstall your current anaconda and install anaconda for python 3.5
